Update _config.yml
exclude vendor: will remove the template nomenclature that is causing the file to abort

'vendor/bundle/ruby/3.1.0/gems/jekyll-3.10.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
             ERROR: YOUR SITE COULD NOT BE BUILT:

Signed-off-by: Sword & Shield <105157794+micaelaniemi@users.noreply.github.com>